[build-system]
requires = ["setuptools", "wheel", "Cython>=3.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PairwiseNameComparator"
version = "0.1.0"
description = "An efficient Python package for all-to-all comparisons of large datasets of names"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []